apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.accountDatabase.dbname }}
  labels:
    app: {{ .Values.accountDatabase.dblabelapp }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.accountDatabase.dblabelapp }}
      tier: {{ .Values.accountDatabase.dbtier }}
  strategy:
    type: {{ .Values.accountDatabase.stype }}
  template:
    metadata:
      labels:
        app: {{ .Values.accountDatabase.dblabelapp }}
        tier: {{ .Values.accountDatabase.dbtier }}
    spec:
      containers:
        - image: "{{ .Values.accountDatabase.image.repository }}:{{ .Values.accountDatabase.image.tag }}"
          name: {{ .Chart.Name }}
          env:
            - name: MYSQL_USER
              value: michaelbolton
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: dockercon2017

          ports:
            - containerPort: {{ .Values.accountDatabase.image.port.Mysqlconport }}
              name: {{ .Values.accountDatabase.image.port.Mysqlconname }}
