apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: wesahelmworkflow
env[1].name: MYSQL_USER
ysqluser: MYSQL_USER
ysqluserval: michaelbolton
ysqlpassword: MYSQL_PASSWORD
ysqlpasswordval: password
ysqlrootpassword: MYSQL_ROOT_PASSWORD
ysqlrootpasswordval: password
ysqldb: MYSQL_DATABASE
ysqldbval: dockercon2017
version: 0.1.0
