
#database Deployment
accountDatabase:
  dbname: account-database
  dblabelapp: office-space
  dbtier: database
  stype: Recreate
  image:
    repository: mysql
    tag: 5.6
    cName: account-database
    cred:
      Mysqluser: MYSQL_USER
      Mysqluserval: michaelbolton
      Values.Mysqlpassword: MYSQL_PASSWORD
      Mysqlpasswordval: password
      Mysqlrootpassword: MYSQL_ROOT_PASSWORD
      Mysqlrootpasswordval: password
      Mysqldb: MYSQL_DATABASE
      Mysqldbval: dockercon2017
    port:
      Mysqlconport: 3306
      Mysqlconname: db

ingress:
  enabled: false
